require "options"
require "user.keymaps"
require "user.plugins"
-- require "user.autocommands"
require "user.cmp"
require "user.lsp"
require "user.treesitter"
require "user.autopairs"
require "user.bufferline"
require "user.telescope"
require "user.neoscroll"
require "user.comment"
require "user.gitsigns"
require "user.lualine"
require "user.nvim-tree"
require "user.neoclip"
require "user.illuminate"
require "user.blankline"
require "user.sonokai"     -- theme
-- require "user.gps"
-- require "user.winbar"


-- vim.cmd "colorscheme nightfox"
