require "options"
require "user.keymaps"
require "user.plugins"
require "user.cmp"
require "user.lsp"
require "user.treesitter"
require "user.autopairs"
require "user.bufferline"
require "user.neoscroll"
require "user.comment"
require "user.gitsigns"
require "user.lualine"
require "user.nvim-tree"


vim.cmd "colorscheme sonokai"
-- vim.cmd "colorscheme nightfox"
