-- THIS FILE IS NOT IN USE
local M = {}
-- Modes
--   normal_mode       = "n",
--   insert_mode       = "i",
--   visual_mode       = "v",
--   visual_block_mode = "x",
--   term_mode         = "t",
--   command_mode      = "c",

-- Some shortcuts to make the conf file more clean
--
-- local map = vim.api.nvim_set_keymap
-- local opts = { noremap = true, silent = true }
-- local expr = { noremap = true, silent = true, expr = true }
--
-- map('n', '<c-s>', ':w<CR>', {})	  -- ctrl-save <- :w    : NORMAL
-- map('i', '<c-s>', '<ESC>:w<CR>a', {})  -- ctrl-save < ESC :w : INSERT
--
-- -- Navigation between buffers
-- map('n', '<c-j>', '<c-w>j', opts)
-- map('n', '<c-h>', '<c-w>h', opts)
-- map('n', '<c-k>', '<c-w>k', opts)
-- map('n', '<c-l>', '<c-w>l', opts)
--
-- -- Keep search matches in the middle of the window
-- map("n", "n", "nzzzv", opts)
-- map("n", "N", "Nzzzv", opts)
--
-- -- Clear matches with Ctrl+l
-- --map("n", "<C-l>", ":noh<Cr>", opts)
--
-- -- Resize windows with Shift+<arrow>
-- map("n", "<S-Up>", ":resize +2<CR>", opts)
-- map("n", "<S-Down>", ":resize -2<CR>", opts)
-- map("n", "<S-Left>", ":vertical resize -2<CR>", opts)
-- map("n", "<S-Right>", ":vertical resize +2<CR>", opts)
--
-- -- Personal Mapping
-- -- map("n", "<.>", "<:>", opts)
-- -- map("c", "<.>", "<:>", opts)
--
